[build]
  command = "npm install --prefix functions"
  publish = "public"

[functions]
  directory = "functions"

[[redirects]]
  from = "/download/*"
  to = "/download.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/relay/*"
  to = "/.netlify/functions/relay/:splat"
  status = 200

[[redirects]]
  from = "/expired"
  to = "/expired.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200